# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [2]:
import numpy as np

from numpy.random import randint as ri

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [16]:
from numpy.random import randint as ri

from math import pow as bm

mat1 = ri(1,10,9).reshape(3,3)

mat2 = ri(1,10,9).reshape(3,3)


            
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat2*mat1)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n",np.power(mat1,3))
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",np.power(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[5 1 3]
 [5 9 6]
 [8 3 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 1 1]
 [4 2 9]
 [1 9 5]]

Addition
------------------
 [[11  2  4]
 [ 9 11 15]
 [ 9 12 13]]

Multiplication
------------------
 [[30  1  3]
 [20 18 54]
 [ 8 27 40]]

Division
------------------
 [[0.83333333 1.         3.        ]
 [1.25       4.5        0.66666667]
 [8.         0.33333333 1.6       ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[ 3  1  7]
 [ 7 23  0]
 [22 -9 14]]

Addition of a scalar (100)
-------------------------
 [[105 101 103]
 [105 109 106]
 [108 103 108]]

Exponentiation, matrix cubed here
----------------------------------------
 [[125   1  27]
 [125 729 216]
 [512  27 512]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[2.23606798 1.         1.73205081]
 [2.23606798 3.         2.44948974]
 [2.82

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [29]:
from numpy.random import randint as ri
import numpy as np
mat1 = ri(1,10,9).reshape(3,3)
mat2 =ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1,axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat2,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = ri(0,99,99)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[3 4 3]
 [7 4 6]
 [4 9 3]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[7 5 7]
 [5 6 7]
 [8 2 4]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 43

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [14 17 12]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [10 17 16]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [ 36 168 108]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [280  60 196]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 4.777777777777778

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 1

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [31]:
from numpy.random import randint as ri
import numpy as np
mat1 = np.zeros([3,3])
modmat1=mat1.reshape(9,1)
print(mat1)

print("modmat",modmat1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
modmat [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### 4.Sort

In [7]:
from numpy.random import randint as ri
import numpy as np


A = np.array(ri(1,100,10))
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [86  6 91 66 24 68 90 24  2 75]

Here is the sorted vector
 -------------------------------------------------- 
 [ 2  6 24 24 66 68 75 86 90 91]


In [5]:
from numpy.random import randint as ri
import numpy as np

M = np.array(ri(0,25,25)) #  5*5 Matrix of random interegrs

N=M.reshape(5,5)
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M.reshape(5,5))
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(N, axis=1, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each co\n",np.sort(N, axis=0, kind='mergesort'))




5x5 Matrix of random integers
 -------------------------------------------------- 
 [[20  9 15 23  2]
 [12 20 23 17 12]
 [24 20  4 17  6]
 [13 21  8  0  7]
 [ 3 12 14  5 19]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 2  9 15 20 23]
 [12 12 17 20 23]
 [ 4  6 17 20 24]
 [ 0  7  8 13 21]
 [ 3  5 12 14 19]]

Here is the sorted matrix along each co
 [[ 3  9  4  0  2]
 [12 12  8  5  6]
 [13 20 14 17  7]
 [20 20 15 17 12]
 [24 21 23 23 19]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [1]:
# Fill the following ***** with appropriate solution

from numpy.random import randint as ri
import numpy as np

a=ri(0,10,10)
b=ri(0,10,10)
c=ri(0,10,10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Max of a:", np.max(a))
print("Max of b:", np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))



a: [0 5 0 7 1 0 0 8 9 3]
b: [1 6 4 9 2 2 6 5 5 2]
c: [0 1 5 7 3 4 4 9 4 6]
Max of a: 9
Max of b: 9
Max of a location: 8
Max of b location: 3
Max of c location: 7
Max of a: 9
Max of b: 9
Max of a location: 8
Max of b location: 3
Max of c location: 7


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [6]:
from numpy.random import randint as ri
import numpy as np

mat1 = ri(1,10,9).reshape(3,3)
mat2 = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n",np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n",np.mod(mat1,mat2))



1st Matrix of random single-digit numbers
----------------------------------------
 [[5 7 6]
 [5 1 4]
 [3 9 3]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[5 9 6]
 [2 8 9]
 [3 4 9]]

Sq-root of 1st matrix using np
------------------
 [[2.23606798 2.64575131 2.44948974]
 [2.23606798 1.         2.        ]
 [1.73205081 3.         1.73205081]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.48413159e+02 1.09663316e+03 4.03428793e+02]
 [1.48413159e+02 2.71828183e+00 5.45981500e+01]
 [2.00855369e+01 8.10308393e+03 2.00855369e+01]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69897    0.84509804 0.77815125]
 [0.69897    0.         0.60205999]
 [0.47712125 0.95424251 0.47712125]]

Modulo reminder using np
 -------------------------------------------------- 
 [[0 7 0]
 [1 1 4]
 [0 1 3]]


### 7.Generating matrices from distributions

In [11]:
from numpy.random import randint as ri
import numpy as np

print("Random number generation (from Uniform distribution)")
print(np.linspace(0,1,num=6).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

print("Random integer vector:",np.random.randint(1,5, size=10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix",np.random.randint(1,5, size=(2,4)))
print("") #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random number generation (from Uniform distribution)
[[0.  0.2 0.4]
 [0.6 0.8 1. ]]
Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.62177579 -0.226924    0.58225133]
 [ 0.09336131 -1.21819772 -0.73315479]
 [-0.84811502  0.18487633  0.62636744]
 [ 0.81681151 -0.42596233 -0.20534801]]
Random integer vector: [4 4 3 4 3 3 1 2 4 1]

Random integer matrix [[2 2 1 2]
 [1 4 2 3]]


20 samples drawn from a dice throw: [4 2 6 2 2 6 5 6 2 3 2 3 3 4 3 5 1 5 3 6]


### 8.Find the nearest value from a given number in an array using NumPy.

In [19]:
from numpy.random import randint as ri
import numpy as np

#Steps
#Create an array of 5 random element from 1 to 12

M=ri(1,12,5)

print(M)
v = 4
n = M.flat[np.abs(M - v).argmin()]
print(n)

[ 8 10  4  5  3]
4


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [11]:

def myvander(myarray):
    
    

        
        d2=[[i*j for j in myarray  ] for i in myarray]
        ns2=np.array(d2)
        print(ns2)
    
        
myarray=np.array([0,1,2])



myvander(myarray)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
